theme: jekyll-theme-minimal
title: 💻🌟
description: Peter Rizk's CV

Technology Strategist: Head of innovation for $20M funded Series B startup for all future PAAS and SAAS offerings. 
Solution Architect: Chief of onshore technology for 500+ employee company that manages application development offshore in India. 
Application Architect: Automated annual review process for an internal division with a workforce of 5500, reducing the annual effort by two-thirds. 
Test Architect: Charged with strategic planning, execution, and support of testing for three-year, $12m project for cloud migration and ICD-10 conversion. 
Best Practice Champion: Conducted dozens of one-on-one, group, whiteboard, and lunch and learn sessions for the benefit of enhancing teams and enterprise knowledge in company-specific innovation and cutting-edge trends.
